### ISSUE TITLE
Smoke Test for milestones - May 2020

### ISSUE THREAD

**Issue by jermyk** [neontribe/gbptm#652]
**A list of current functions to check new milestones against**

Does the milestone work correctly?

Does the list of current functions still work, if they are linked, or are improvements to existing functionality.

https://gbptm.neontribe.now.sh/

**Comment by jermyk** [comment]
**Location**

- [x] Does the toilet map recognise users location when accessing the site

- [x] User can see Use our Loos and Domestos logos 

- [x] User can see opt in with Google Analytics (In the footer menu on  mobile devices)

- [x] User can see opt in with Adobe Analytics (In the footer menu on  mobile devices)

- [x] User can save any changes and close the opt in page

**Comment by jermyk** [comment]
**Nearest toilet options**

- [x] User should see the 5 nearest toilets to their location

- [x] Select Add a toilet. User should be prompted to log in or sign up

- [x]  If user has logged in previously, the site will tell them which email address they logged in with and allow them to progress

- [x] If not the site will prompt them for email address and password details

**Comment by jermyk** [comment]
**Adding a toilet**

- [x] Select Add a toilet option form the menu on the left of the page

- [x] Follow the instructions for adding a toliet, remembering to use the crosshair to align the toilet to the map ansd  selecting the relevant name, facilities, notes and lat/long details if known. 

- [x] Add the toilet to the map

- [x] User should see a new green animated pin added to the map where the new toilet has been added

- [x] Return to the home page by clicking on the GBTM logo at the top of the menu

- [x] User should see the new toilet added as part of the nearest toilets option

- [x] Total number of nearest toilets should still number 5

**Comment by jermyk** [comment]
**Preferences**

- [x] Select the preferences link from the footer menu

- [x] User should see a list of preferences they can select when searching for a toliet

- [x] Select a specific requirement and save the changes

- [x] Toilet map should display a message to show preferences have been updated

- [x] Return to the homepage by selecting the GBTM logo at the top of the menu

- [x] The User should now see a greater selection of toilets displaying on the map that when selected show the preferences the user updated

**Comment by jermyk** [comment]
**Privacy Policy**

- [x] Select the privacy policy link in the footer menu

- [x] User should see latest version of the GBPTM privacy policy and can scroll to the bottom of the page

**Comment by jermyk** [comment]
**About**

- [x] Select the About link from the footer menu

- [x] User should see information about the map

- [x] User should see information - Use our Loos

- [x] Links in the information take the user to another page in a seperate tab on their browser

- [x] If user closes the information tab they return to the gbptm

- [x] User should see information - Thinking about adding a toilet?

- [x] User should be able to scroll up and down the page

- [x] Return to the home page by clicking on the GBTM logo at the top of the menu

**Comment by jermyk** [comment]
**More Info**

- [x] In the nearest toilets section click on the link  More info 

- [x] User should see details of the toilet they have selected

**Edit Toilet**

- [ ] User can edit the details from the drop down lists

- [ ] User can select radio buttons where applicable

- [ ] User can add a fee

- [ ] User can add free text note

- [ ] User can update the details of the toilet

- [ ] User can remove the toilet if required

- [ ] User can scroll on this page

**Comment by jermyk** [comment]
**Removing a toilet**

- [x] Select the toilet to be removed by double clicking the pIn from the map

- [x] Select edit toilet

- [x] Scroll to the foot of the page

- [x] Select Remove toilet

- [x] Add some free text as to why the toilet is being removed

- [x] Click on the Remove it button

- [x] When the user reactivate the map by clicking or dragging the pin should disappear

**Comment by jermyk** [comment]
**Open street map**

- [x] Map renders and user can see "a map"

- [x] User can drag the map up and down, left to right

- [x] Map renders correctly when user drags as above

**Where am I?**

- [x] In the top left corner of the page under the zoom icons a "show me where I am" figure should display

- [x] Selecting by touch or clicking with a mouse on the "show me" figure should centre the map and a black cross should be visible in the centre of the users page

- [x] This should be the users current location

**Zoom**

- [x] Top left corner of the map should display + & - sign for zooming in and out

- [x] Zoom in to this point to confirm this is correct

- [x] User can zoom into a place on the map

- [x] User can zoom out of a place on the map

- [x] Spinner displays under zoom icons when zooming in and out

- [x] When user zooms out, more toilets in the area should appear

- [x] Pins may display numbers corresponding to the number of toilets in that area

- [x] Selecting a numbered pin should break out into the same number of individual pins (one for each toilet)

- [x] Selecting a pin displays the toilet detail on the left of the page (on desktop), and the edit option is available (see section for editing toilet)

- [x] On a mobile device touching the pin displays the toilet detail on the main screen, user can return to the general map by selecting the back arrow on their device

- [x] Zooming in reduces the number of pins visible and breaks down to individual toilets where applicable

- [x] User may still view numbered pins when zoomed in

- [x] Selecting a pin when zoomed in displays the toilet information on the left of the page (on dektop)

- [x] Selecting a pin when zoomed in on a mobile device displays the toilet information on the main page

**Comment by jermyk** [comment]
**Search**

- [x] The search icon and free text field should display in the top right hand corner of the page

- [x] Click on/select the icon

- [x] Option to add place name or postcode should display

- [x] Add a valid postcode and hit enter/Go

- [x] Map should render corectly and navigate to the relevant place

- [x] toilets should display if they are available in the area selected

- [x] Repeat the same search command with a specific street name

- [x] Search should return options if there are more than one street with that name

- [x] User can select the street they requested

- [x] Map renders correctly when street is selected and user can see their choice on the map

- [x] Chosen street name should display in the centre of the map with the cross hair **+** visible

 - [x] Use should be able to perform all of the zoom functionality as described in the **Zoom ** section above

**Comment by jermyk** [comment]
**Search**

- [x] The search icon and free text field should display in the top right hand corner of the page

- [x] Click on/select the icon

- [x] Option to add place name or postcode should display

- [x] Add a valid postcode and hit enter/Go

- [x] Map should render corectly and navigate to the relevant place

- [x] toilets should display if they are available in the area selected

- [x] Repeat the same search command with a specific street name

- [x] Search should return options if there are more than one street with that name

- [x] User can select the street they requested

- [x] Map renders correctly when street is selected and user can see their choice on the map

- [x] Chosen street name should display in the centre of the map with the cross hair **+** visible

 - [x] Use should be able to perform all of the zoom functionality as described in the **Zoom ** section above

**Comment by jermyk** [comment]
**Password Reset**

- [x] From the login page select "Don't remember your password?"

- [x] User is prompted to add their email address/displays autofilled email address

- [x] Select Send Email

- [x] A message should display "WE'VE JUST SENT YOU AN EMAIL TO RESET YOUR PASSWORD"

- [x] User should receive a password reset email in their inbox with the option to confirm they requested the password reset

- [x] Confirming this takes them to the Change Password page where the user  add and confirm a new password

- [x] On completing this a message displays telling the user they have successfully reset their password

**Comment by jermyk** [comment]
**Supported Browsers**

Desktop - Windows 10 - Chrome 

Android  - mobile device

**End of Test**

**Comment by jermyk** [comment]
**Safari**

- [ ] Map took a long time to render when accessing the site

**Comment by jermyk** [comment]
**Header**

- [ ] Mobile device - Burger menu slides a full height drawer menu in to view when selected. (Menu icon turns red at this point. When selected again menu is closed. Menu icon stays red until page is refreshed.

**Comment by jermyk** [comment]
**Footer**

 [ ] - The cookie banner. When you first load the website and haven't dismissed the cookie preferences banner (which appears at the bottom of the page), the cookie banner should appear. You can also make it appear by clicking on the "Cookie preferences" link from the footer.

**Comment by jermyk** [comment]
**Filters**

 - [ ]  You should be able to filter by the various filters. 
Note that the "Free" filter will be changing — so you can ignore how accurate that is for now.

**Comment by jermyk** [comment]
**View Details**

- [ ] Clicking on a map pin will bring up a details panel. From there you can also click "More details" to view more

**Comment by jermyk** [comment]
**Devices tested on**

- [ ] Desktop. Windows 10
- [ ] Desktop Windows 7 Internet Explorer
- [ ] Android device. Samsung Galaxy mobile.
- [ ] iPad 7th generation - Safari browser

**Comment by jermyk** [comment]
**Observations**
- [ ] If user is viewing toilet details and then clicks cookie preferences, the details hide the preferences options.
- [ ]

**Comment by jermyk** [comment]
**IE11**
- [ ] Logo is squashed and box appears around text 
![Screenshot_052120_093825_AM](https://user-images.githubusercontent.com/4446325/82540349-d1513e80-9b46-11ea-9a89-5f678c35e448.jpg)

- [ ] After reading the about page with the cookie banner still visible, the user closed the cookie banner in order to continue reading the page.
![Screenshot_052120_093934_AM](https://user-images.githubusercontent.com/4446325/82540438-fb0a6580-9b46-11ea-97d9-53ddde1812f2.jpg)

-[ ] Footer displaying in privacy policy
![Screenshot_052120_094025_AM](https://user-images.githubusercontent.com/4446325/82540528-19706100-9b47-11ea-858a-d3f68f477b2e.jpg)

**Comment by jermyk** [comment]
@falconx 
I believe I'm upto date on what you've asked me to look at, standing by for any further changes to test?

**Comment by falconx** [comment]
@jermyk Thanks! I've got a branch where the IE11 + Safari issues are hopefully resolved — I'll let you know when this is ready.

I've just merged the Add + Edit pages which, other than opening hours, should both now be functional. If you could test those that would be great :)

**Comment by jermyk** [comment]
**Add & Edit Pages**

- [ ] Edit an existing loo

- [ ] Add a new loo

 **Devices tested on**

- [x] Desktop. Windows 10 Chrome browser
- [x] Desktop Windows 7 Internet Explorer
- [x] Android device. Samsung Galaxy mobile.
- [x] iPad 7th generation - Safari browser

**Comment by jermyk** [comment]
@falconx 
To add a new loo I need to log in in and I'm unable to do so via the route suggested? (Interestingly I can login to edit a loo, which is a different route). 
![Screenshot_052120_120651_PM](https://user-images.githubusercontent.com/4446325/82553232-8ee62c80-9b5b-11ea-8b52-022f3541f0a4.jpg)

**Comment by falconx** [comment]
@jermyk ah, that section is about to change so that "Add a Loo" becomes a link instead of collapsible section. I recommend using the "Add Loo" link from the header.

**Comment by jermyk** [comment]
@falconx 

Currently the page looks like it's saving changes, but doesn't acdtually do so?
![Untitled_Clipping_052120_030043_PM](https://user-images.githubusercontent.com/4446325/82566453-d8db0c80-9b73-11ea-9b2a-f39bcb0cd5ee.jpg)

![Screenshot_052120_030003_PM](https://user-images.githubusercontent.com/4446325/82566392-c1038880-9b73-11ea-8860-dbf8cfe981cc.jpg)

**Comment by falconx** [comment]
Add toilet should create a new entry and edit toilet should modify one however, I'm currently still working on redirecting the user from the add form to the new entry page and adding notifications to let the user know what's happening.

**Comment by jermyk** [comment]
@marxian 
User added a toilet 
![Screenshot_061520_025049_PM](https://user-images.githubusercontent.com/4446325/84665323-9b219780-af17-11ea-889e-c34c29da2816.jpg)
After adding the toilet user could not see the pin
When user selected add a toilte the pin displayed and th user could see the details
![Screenshot_061520_025210_PM](https://user-images.githubusercontent.com/4446325/84665503-d2904400-af17-11ea-8c31-d7a57a1e3fd4.jpg)
Should the pin display when the toilet details are on display?

**Comment by jermyk** [comment]
@marxian 

The plot thickens, I can see the added toilet on my mobile device
![Screenshot_061520_032015_PM](https://user-images.githubusercontent.com/4446325/84668576-b7bfce80-af1b-11ea-9ba0-96f1e92ada56.jpg)

**Comment by jermyk** [comment]
@marxian 

**Some observations in IE11 on a Windows 7 machine**

**Error when saving toilet**
![Screenshot_061620_044407_PM](https://user-images.githubusercontent.com/4446325/84796496-9846a580-aff0-11ea-897e-b5a3ec683e0e.jpg)

![Screenshot_061620_044627_PM](https://user-images.githubusercontent.com/4446325/84796766-ebb8f380-aff0-11ea-9bed-f268f77b8a32.jpg)

**Squashed crosshair**
![Screenshot_061620_044747_PM](https://user-images.githubusercontent.com/4446325/84796914-1c009200-aff1-11ea-9daa-6178a8f1e9c1.jpg)

**Comment by marxian** [comment]
@jermyk I believe I've fixed "saving a loo"

The squashed crosshair is beyond my skill, so I'm going to let it ride.

**Comment by jermyk** [comment]
@marxian 

I was able to add toilets successfully, but still noticed an error appearing in the console?
Are these related?
This was on Windows 10 - Chrome laptop.

![Screenshot_061820_112820_AM](https://user-images.githubusercontent.com/4446325/85009720-d067f880-b156-11ea-8a9c-8cd001f4e1fb.jpg)

**Comment by jermyk** [comment]
@marxian 

I've retested the IE11 saving toilet issue but can still see the same error?
![Screenshot_061820_114747_AM](https://user-images.githubusercontent.com/4446325/85011513-87fe0a00-b159-11ea-9b0a-b728d5233177.jpg)

**Comment by marxian** [comment]
That looks like the Adobe tracking scripts.
